name: Belaldesign
favicon: null
layout_spectrum: 0.00308
typography_spectrum: 0.37192
title: Belal Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0b267'
    - '#dd4134'
    - '#359bcb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
