name: Belaldesign
favicon: null
layout_spectrum: 0.00308
typography_spectrum: 0.37192
title: Belal Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d1e'
    - '#fefefe'
    - '#626667'
    - '#393c31'
    - '#b4b6b5'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.7297249715775251
purpose: []
