name: Belaldesign
favicon: null
layout_spectrum: 0.6041202400811017
typography_spectrum: 0.1893305853009224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5300006414763629
  lightness: 0.9300725697539747
  saturation: 0.2893252051435411
  rhythmicContrast: 0.7297249715775251
purpose: []
